sprint1/step2
AnnaKochetkova/react-burger pull request #2
Opened 2022-03-27 11:28 UTC by AnnaKochetkova

2022-03-28 12:16 UTC, ChrisGerBy requested changes
Здравствуйте!
Достойная работа!
Функционал реализован. 
- Все перечисленные функциональности работают.
- Вы научились писать функциональные компоненты и применять хуки useState, useEffect, useCallback.

Однако, есть некоторые моменты, которые нужно исправить, прежде чем идти дальше:

- запрос к API должен происходить единожды;
- для всех компонентов, принимающих пропсы, необходимо прописать propTypes. Это требование задания на данном этапе. 
- использовать иконки из подключенной библиотеки;
- исправить структуру папок (см. комментарии).

Также есть несколько рекомендаций по улучшению производительности кода, по его оптимизации - см. подробности в комментариях.

Желаю успехов в исправлении!

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/modal-overlay.tsx
> +const ModalOverlay = (props: IModalOverlayProps) => {
**Надо исправить**
папка компонента ModalOverlay должна находиться, согласно заданию, в директории src/components. Вынесите, пожалуйста, этот компонент и его стили в отдельную папку.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/order-details.tsx
> +const OrderDetails = () => {
**Надо исправить**
папка компонента OrderDetails должна находиться, согласно заданию, в директории src/components. Вынесите, пожалуйста, этот компонент и его стили в отдельную папку.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/Ingredient-details.tsx
> +const IngredientDetails = ({ingredients}: IIngredientDetails) => {
**Надо исправить**
папка компонента IngredientDetails должна находиться, согласно заданию, в директории src/components. Вынесите, пожалуйста, этот компонент и его стили в отдельную папку.
Также будет лучше назвать файл в стиле  kebab-case (первая буква маленькая), как у Вас названы и другие файлы, чтобы одинаково было по всему проекту.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/app/app.tsx
>  import logo from './logo.svg';
**Можно лучше**
неиспользуемый импорт. Для сохранения чистоты кода лучше убирать неиспользуемые части кода.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +    const url = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить**
Cогласно заданию,
```
Запрос к API за информацией об ингредиентах работает корректно и выполняется единожды при монтировании компонента `App`;
```

В Вашей реализации запрос делается дважды.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/45519864/160388899-9888d555-6006-4027-ac85-cc1153d56cef.png">

Один раз Вы запрашиваете данные из компонента BurgerConstructor, второй раз из BurgerIngredients.
Нужно оставить один запрос. В задании уже есть подсказка, в какой компоненте необходимо делать запрос. Плюс также если Вы видите, что два компонента используют одни и те же данные, то необходимо, чтобы эти данные к ним попадали из пропсов, а данные эти были в их родительской компоненте. Это называется "подъем состояния" в терминологии реакта. 
Вот тут можно изучить: https://ru.reactjs.org/docs/lifting-state-up.html

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
>  import data from '../../utils/data';
**Можно лучше**
уберите, пожалуйста, неиспользуемый импорт.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +const BurgerConstructor = (props: IBurgerConstructorProps) => {
**Надо исправить**
typescript - это прекрасно. Однако, согласно заданию, необходимо прописать propTypes для передаваемых пропсов. Пожалуйста, ДЛЯ ВСЕХ КОМПОНЕНТОВ, принимающих пропсы, пропишите propTypes. 
https://ru.reactjs.org/docs/typechecking-with-proptypes.html

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +        const handlerEvent = (e: KeyboardEvent) => {
**Можно лучше**
рекомендую переименовать функцию точнее, потому что если вдруг в будущем понадобиться хэндлить еще другие события (скролл, клик и т. д.), то это название будет вводить в заблуждение: "Какое именно событие тут имеется в виду?"

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/order-details.tsx
> +            <img className={styles.orderImg} src={order} alt="order" />
**Надо исправить**
согласно заданию, необходимо использовать иконки из  подключенной UI-библиотеки: 
https://yandex-praktikum.github.io/react-developer-burger-ui-components/docs/icons

P.S. после исправления не забудьте, пожалуйста, также удалить неиспользуемые файлы из папки images.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/modal-header.tsx
> +                </svg>
**Надо исправить**
согласно заданию, необходимо использовать иконки из  подключенной UI-библиотеки: 
https://yandex-praktikum.github.io/react-developer-burger-ui-components/docs/icons

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
>                          })
**Можно лучше**
Вот эта часть кода - итерация по массиву ингредиентов - у Вас дублируется трижды.
Один раз - Вы возвращаете <Ingredient /> - для булок, второй раз - для соусов, третий - для начинок.
Оптимальный вариант - это пройти ОДИН раз по массиву - и рассортировать все ингредиенты по нужным категориям (булки / соусы / начинки). 
Вы можете реализовать это, использовав, например, метод массива reduce.
Кроме того, весьма полезным здесь может быть хук useMemo реакта для хранения этих отсортированных данных.
Идея такова:
1. получить массив ВСЕХ ингредиентов вперемежку;
2.  сделать их сортировку по типу и сохранить каждый тип в отдельную переменную;
3. при отображении данных в блоке return ( ... ), итерировать не весь список ингредиентов, а уже отсортрованные по типу.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    }, [request])
**Можно лучше**
Вы верно использовали хук useCallback! Хорошая работа!
Однако, так как Вы используете функцию `request` всего в одном месте, все ее содержимое можно поместить напрямую внутрь useEffect.
```
useEffect(() => {
   try {
    ...
   } catch(e) {
    ....
  } 
}, [ ])
```

В данном случае будет понятно, что эта логика должна выполниться единожды - при монтровании. Больше нигде в этом компоненте эта функция не участвует, так и нет смысла хранить отдельную переменную для этой функции, плюс еще вызывать хук useCallback.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/Ingredient-details.tsx
> +    ingredients: IListItemIngredient | undefined;
**Надо исправить**
неточное название пропса. Читая `ingredients`, читающий код программист ожидает скорее массив ингредиентов, а не данные об одном ингредиенте. Поэтому рекомендую Вам дать более точное название пропсе.

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +    if(open === false && modalRoot !== null) return null;
**Можно лучше**
согласно прописанному типу для `open`, внутри будет лежать только булевое значение.
В таком случае проверка здесь может быть сведена только к
```
    if(!open && modalRoot !== null) return null;
```

2022-03-28 12:16 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +        }
**Можно лучше**
Обращаться к DOM-у в Реакт - плохая практика. Используется кра-а-а-айне редко.

Эту же логику можно реализовать лишь добавив нужный класс к элементу, например:
```
  return ( 
    <div className={ open ? styles. open : styles.closed } />
```

Либо использовать ref: https://ru.reactjs.org/docs/refs-and-the-dom.html

Изменение DOM-а - тяжеловесная операция. Разработчики Реакта как раз и стремились ее облегчить. В связи с этим необходимо задуматься о том, нужно ли данное преобразование в Вашем проекте и если да, то каким из выше перечисленных способов его можно выполнить.

2022-03-28 12:27 UTC, AnnaKochetkova commented on src/components/modal/modal-overlay.tsx
> +const ModalOverlay = (props: IModalOverlayProps) => {
Подскажите пожалуйста, а зачем выносить подложку в отдельную папку? Я, к сожалению, не нашла этого в задании. Получается в отдельные папки должны пойти подложка и одно из модальных окон?

2022-03-28 15:47 UTC, AnnaKochetkova commented on src/components/burger-constructor/burger-constructor.tsx
> +const BurgerConstructor = (props: IBurgerConstructorProps) => {
Наставник в Слаке говорил, если использовать TypeScript, то использовать ProppTypes уже не нужно.

2022-03-28 15:49 UTC, AnnaKochetkova commented on src/components/modal/modal.tsx
> +        }
У меня, к сожалению, не получается это сделать без обращения к DOM`у. Я бы еще подумала как это можно реализовать, но пока что не знаю. Гуглила, говорят, что мой способ не очень хороший, но и не дают ответа как лучше это заменить. Я не знаю как сделать это через ref`ы

2022-03-29 07:59 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +        }
В данном случае этот useEffect создает Вам дополнительный бажок - скачок контента body при открытии модалки. В чем смысл добавления этих стилей к body? Действительно ли они нужны? Если подумать, то реализация портала не должна вызывать каких-то побочных изменений стилей. Точнее крайне редко, в каких-то очень необычных случаях это может понадобится. Но здесь логика весьма проста: клик - показать портал, клик / Esc - закрыть портал. Погуглите примеры реализаций портала, изучите другие варианты кода. Я думаю, что при открытии/закрытии в 99% случаев не будет добавления/удаления стилей на другие элементы.
Вот, как у меня выглядит приложение, если оставить Вашу имплементацию и если убрать вообще этот useEffect: 
https://www.awesomescreenshot.com/video/8115908?key=04ad5a62d65676c36db2ad919ff91cff

2022-03-29 08:00 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +const BurgerConstructor = (props: IBurgerConstructorProps) => {
Принято.

2022-03-29 08:07 UTC, AnnaKochetkova commented on src/components/modal/modal.tsx
> +        }
Хорошо. Я вас поняла. Получается я могу просто удалить этот UseEffect и оставить без него?

2022-03-29 08:15 UTC, ChrisGerBy reviewed
Здравствуйте!
Ваша работа принята. 
Я оставила Вам еще несколько "Можно лучше" комментариев, которые помогут Вам сделать еще несколько улучшений качества кода. Рекомендую проработать их прежде, чем идти дальше.

Желаю успехов в дальнейшем обучении!

2022-03-29 08:15 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +    list: any[];
**Можно лучше**
следует стараться не использовать any, тем более что в этом случае Вы точно знаете, что сюда приходит, какой тип данных. И у Вас уже есть созданный тип/интерфейс для этого.

2022-03-29 08:15 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    type: "bun" |"sauce" | "main";
**Можно лучше**
Для подобных случаев в typescript есть enum.
Можете попробовать применить в данном случае.
 https://www.typescriptlang.org/docs/handbook/enums.html

2022-03-29 08:15 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    list: any[];
**Можно лучше**
 постарайтесь использовать конкретный тип данных вместо any. У Вас уже есть созданный тип/интерфейс для этого.

2022-03-29 08:15 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
**Можно лучше**
метод map в данном случае не совсем точен, так как он  предполагает, что для каждого элемента что-то возвращается.
Что у Вас вернется для  элементов с типом bun или sauce? 
Поэтому здесь точнее было бы использовать другие методы массива. Вспомните, как Вы делали сортировку в BurgerIngredients. В данном случае можете использовать подобную логику. 
Это позволит Вам:
1. точнее использовать метод массива вместо map
2. для верхней и нижней булки заменить вручную прописанные данные реальными данными булок.

2022-03-29 08:15 UTC, ChrisGerBy commented on src/components/modal/modal.module.css
> +     */
**Можно лучше**
не забывайте подчищать неиспользуемый закомментированный код. Если же Вы планируете его использовать в будущем, то рекомендую писать комментарий с пояснением, когда/при каких условиях этот код будете использовать.

2022-03-29 08:15 UTC, ChrisGerBy commented on src/utils/group-by.ts
> +            if (prevValue[currKey] === undefined){
**Можно лучше**
любите Вы точное сравнение с undefined ;) 
Почему бы не использовать   ` if (!prevValue[currKey]` - это читается как `если в prevValue  нет данных с ключом currKey, то ... `? Короче, читабельнее, абсолютно точно выполняет свою функцию.

2022-03-31 12:00 UTC, merged